/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Openbd {
  onix?: {
    /**
     * 識別情報(ISBN)
     */
    ProductIdentifier?: {
      /**
       * IDの種類[ISBN固定]
       */
      ProductIDType?: string;
      /**
       * ISBN（13桁）
       */
      IDValue?: string;
    };
    /**
     * ISBN（13桁）
     */
    RecordReference?: string;
    /**
     * 出版社に関する情報
     */
    PublishingDetail?: {
      /**
       * 長期品切情報:長期品切れの場合、08:Inactiveを記入
       */
      PublishingStatus?: string;
      /**
       * 商品の出版に関する日付情報
       */
      PublishingDate?: {
        /**
         * 発売日の種類
         */
        PublishingDateRole?: string;
        /**
         * 発売日
         */
        Date?: string;
      }[];
      /**
       * 「発行元出版社」に関する情報
       */
      Imprint?: {
        /**
         * 「発行元出版社」名
         */
        ImprintName?: string;
        /**
         * 「発行元出版社」コード
         */
        ImprintIdentifier?: {
          /**
           * ID
           */
          IDValue?: string;
          /**
           * IDタイプ
           */
          ImprintIDType?: string;
        }[];
      };
      /**
       * 「発行元出版社」と異なる場合、「発売元出版社」についての情報
       */
      Publisher?: {
        /**
         * Publisher 【出版社】 に固定
         */
        PublishingRole?: string;
        /**
         * 「発売元出版社」名
         */
        PublisherName?: string;
        /**
         * 「発売元出版社」コード
         */
        PublisherIdentifier?: {
          /**
           * ID
           */
          IDValue?: string;
          /**
           * IDタイプ
           */
          PublisherIDType?: string;
        }[];
      };
    };
    /**
     * 削除フラグ
     */
    NotificationType?: string;
    /**
     * 市場における商品の出版状況、供給等
     */
    ProductSupply?: {
      /**
       * 扱い社に関する情報
       */
      MarketPublishingDetail?: {
        /**
         * 00:Unspecifiedを記入する
         */
        MarketPublishingStatus?: string;
        /**
         * 取次会社取り扱いと配本の有無について
         */
        MarketPublishingStatusNote?: string;
        /**
         * 扱い社
         */
        PublisherRepresentative?: {
          /**
           * 08扱い社に固定
           */
          AgentRole?: string;
          /**
           * 扱い社名
           */
          AgentName?: string;
          /**
           * 扱い社コード
           */
          AgentIdentifier?: {
            /**
             * 01:独自コードに固定
             */
            AgentIDType?: string;
            /**
             * コードの名前
             */
            IDTypeName?: string;
            /**
             * コード
             */
            IDValue?: string;
          }[];
        }[];
      };
      /**
       * 商品のアベイラビリテイ（入手可能性）や価格、その他の供給状況
       */
      SupplyDetail?: {
        /**
         * 返品条件について
         */
        ReturnsConditions?: {
          /**
           * 「ONIX返品条件コード」 に固定
           */
          ReturnsCodeType?: string;
          /**
           * 条件コード
           */
          ReturnsCode?: string;
        };
        /**
         * 「近刊情報センター」では、99に固定
         */
        ProductAvailability?: string;
        /**
         * 価格（単価）について
         */
        Price?: {
          /**
           * 価格タイプ
           */
          PriceType?: string;
          /**
           * 価格
           */
          PriceAmount?: string;
          /**
           * 通貨
           */
          CurrencyCode?: string;
          /**
           * 特価期限
           */
          PriceDate?: {
            /**
             * 価格の種類
             */
            PriceDateRole?: string;
            /**
             * 日付
             */
            Date?: string;
            /**
             * 価格
             */
            Price?: string;
          }[];
        }[];
      };
    };
    /**
     * 商品に関する情報
     */
    DescriptiveDetail?: {
      /**
       * 表記に利用する言語
       */
      Language?: {
        /**
         * 価格の種類
         */
        LanguageCode?: string;
        /**
         * 言語コード
         */
        LanguageRole?: string;
        /**
         * 国コード
         */
        CountryCode?: string;
      }[];
      /**
       * 商品の「書名」を設定
       */
      TitleDetail?: {
        /**
         * タイトルの種類[01に固定]
         */
        TitleType?: string;
        /**
         * タイトルの要素
         */
        TitleElement?: {
          /**
           * タイトルのレベル[01に固定]
           */
          TitleElementLevel?: string;
          /**
           * 書名
           */
          TitleText?: {
            /**
             * 読み仮名
             */
            collationkey?: string;
            /**
             * 書名
             */
            content?: string;
          };
          /**
           * サブタイトル
           */
          Subtitle?: {
            /**
             * 読み仮名
             */
            collationkey?: string;
            /**
             * 書名
             */
            content?: string;
          };
          /**
           * シリーズ巻次:<TitleElementLevel>毎に該当する巻次があれば、文字列として記入する
           */
          PartNumber?: string;
        };
      };
      /**
       * 判型
       */
      ProductForm?: string;
      /**
       * 判型の詳細コード
       */
      ProductFormDetail?: string;
      /**
       * シリーズに関する情報
       */
      Collection?: {
        /**
         * 種類コード[10に固定]
         */
        CollectionType?: string;
        /**
         * 「配本回数」について
         */
        CollectionSequence?: {
          /**
           * 配本回数コード[01:完結フラグ,03:配本回数]
           */
          CollectionSequenceType?: string;
          /**
           * コードが完結フラグの場合、完結フラグと記入する
           */
          CollectionSequenceTypeName?: string;
          /**
           * 配本回数
           */
          CollectionSequenceNumber?: string;
        };
        /**
         * シリーズタイトル
         */
        TitleDetail?: {
          /**
           * タイトルの種類[01に固定]
           */
          TitleType?: string;
          /**
           * シリーズ・レーベルの名前
           */
          TitleElement?: {
            /**
             * シリーズの種類
             */
            TitleElementLevel?: string;
            /**
             * シリーズ名
             */
            TitleText?: {
              /**
               * 読み仮名
               */
              collationkey?: string;
              /**
               * タイトル
               */
              content?: string;
            };
            /**
             * シリーズの巻次
             */
            PartNumber?: string;
          }[];
        };
      };
      /**
       * 商品に関連する（数値的）範囲、程度など
       */
      Extent?: {
        /**
         * 数値の種類[11はページ数]
         */
        ExtentType?: string;
        /**
         * 単位[03ページに固定]
         */
        ExtentUnit?: string;
        /**
         * 値
         */
        ExtentValue?: string;
      }[];
      /**
       * タテ・ヨコの実寸
       */
      Measure?: {
        /**
         * 数値の種類[01縦/02横]
         */
        MeasureType?: string;
        /**
         * 単位[mmに固定]
         */
        MeasureUnitCode?: string;
        /**
         * 値
         */
        Measurement?: string;
      }[];
      /**
       * 商品の著者情報
       */
      Contributor?: {
        /**
         * 著者区分
         */
        ContributorRole?: string[];
        /**
         * 表示順序
         */
        SequenceNumber?: string;
        /**
         * 著者名
         */
        PersonName?: {
          /**
           * 読み仮名
           */
          collationkey?: string;
          /**
           * タイトル
           */
          content?: string;
        };
        /**
         * 著者略歴
         */
        BiographicalNote?: string;
      }[];
      /**
       * セット商品分売可否
       */
      ProductComposition?: string;
      /**
       * 商品の対象読者を示す方法
       */
      Audience?: {
        /**
         * 読者コード種類
         */
        AudienceCodeType?: string;
        /**
         * 読者コード
         */
        AudienceCodeValue?: string;
      }[];
      /**
       * 商品の主題、テーマ、カテゴリなど
       */
      Subject?: {
        /**
         * カテゴリ
         */
        SubjectSchemeIdentifier?: string;
        /**
         * 78 or 79 の場合に、「Cコード」または「ジャンルコード」
         */
        SubjectCode?: string;
        /**
         * メーンとなるSubjectのカテゴリ
         */
        MainSubject?: string;
        /**
         * キーワード
         */
        SubjectHeadingText?: string;
      }[];
      /**
       * 付録の有無
       */
      ProductPart?: {
        /**
         * 付録の数量[1に固定]
         */
        NumberOfItemsOfThisForm?: string;
        /**
         * 付録コード[00に固定]
         */
        ProductForm?: string;
        /**
         * 付録の内容
         */
        ProductFormDescription?: string;
      }[];
    };
    /**
     * 商品の付帯項目
     */
    CollateralDetail?: {
      /**
       * ONIXデータを補助する販促情報や追加情報などのデジタルデータ
       */
      SupportingResource?: {
        /**
         * 種類[01書影07商品イメージ]
         */
        ResourceContentType?: string;
        /**
         * [03静止画に固定]
         */
        ResourceMode?: string;
        /**
         * [01に固定]
         */
        ContentAudience?: string;
        /**
         * 補助リソースのバージョン
         */
        ResourceVersion?: {
          /**
           * フルURI
           */
          ResourceLink?: string;
          /**
           * [02に固定]
           */
          ResourceForm?: string;
          /**
           * ファイル名とファイル形式
           */
          ResourceVersionFeature?: any[];
        }[];
      }[];
      /**
       * 内容紹介
       */
      TextContent?: {
        /**
         * テキスト
         */
        Text?: string;
        /**
         * 種類コード
         */
        TextType?: string;
        /**
         * 意図されている読者
         */
        ContentAudience?: string;
      }[];
    };
  };
  /**
   * 版元独自書誌
   */
  hanmoto?: {
    /**
     * 公開日
     */
    datekoukai?: string;
    /**
     * 最終更新日
     */
    datemodified: string;
    /**
     * 最終作成日
     */
    datecreated?: string;
    /**
     * 出版日
     */
    dateshuppan?: string;
    /**
     * 読者書き込みページ数
     */
    dokushakakikomipagesuu?: number;
    /**
     * 販売区分
     */
    kubunhanbai?: boolean;
    /**
     * 本の綴じ方
     */
    toji?: string;
    /**
     * 在庫ステータス
     */
    zaiko?: number;
    /**
     * 版
     */
    han?: string;
    /**
     * TRC用ジャンルコード
     */
    genrecodetrc?: number;
    /**
     * TRC用児童ジャンルコード
     */
    genrecodetrcjidou?: number;
    /**
     * TRC用備考
     */
    bikoutrc?: string;
    /**
     * NDC(日本十進分類法)
     */
    ndccode?: string;
    /**
     * 105文字程度の解説
     */
    kaisetsu105w?: string;
    /**
     * 版元からひとこと
     */
    hanmotokarahitokoto?: string;
    /**
     * 刊行形態
     */
    kankoukeitai?: string;
    /**
     * ラノベフラグ
     */
    lanove?: boolean;
    /**
     * まえがきなど
     */
    maegakinado?: string;
    /**
     * 試し読みフラグ
     */
    hastameshiyomi?: boolean;
    /**
     * 絶版日
     */
    datezeppan?: string;
    /**
     * 受賞情報
     */
    jushoujouhou?: string;
    /**
     * 重版予定日
     */
    datejuuhanyotei?: string;
    /**
     * 原書名
     */
    genshomei?: string;
    /**
     * 関連書
     */
    kanrensho?: string;
    /**
     * 追記
     */
    tsuiki?: string;
    /**
     * 帯の内容
     */
    obinaiyou?: string;
    /**
     * ルビの有無
     */
    rubynoumu?: boolean;
    /**
     * 付録その他
     */
    furokusonota?: string;
    /**
     * 付録コード
     */
    furoku?: number;
    /**
     * 雑誌コード
     */
    zasshicode?: string;
    /**
     * 類書・競合書
     */
    ruishokyougousho?: string;
    /**
     * その他の特記事項
     */
    sonotatokkijikou?: string;
    /**
     * 月号・号数
     */
    gatsugougousuu?: string;
    /**
     * 読者書き込み
     */
    dokushakakikomi?: string;
    /**
     * 関連書ISBN
     */
    kanrenshoisbn?: string;
    /**
     * 別称資料?
     */
    bessoushiryou?: string;
    /**
     * 重版情報
     */
    jyuhan?: {
      /**
       * 重版日
       */
      date: string;
      /**
       * 更新日時
       */
      ctime?: string;
      /**
       * 刷数
       */
      suri?: number;
      /**
       * コメント
       */
      comment?: string;
    }[];
    /**
     * 著者補足情報
     */
    author?: {
      /**
       * 独自区分
       */
      dokujikubun: string;
      /**
       * リストの番号
       */
      listseq: number;
    }[];
    /**
     * 書評情報
     */
    reviews?: {
      /**
       * 版
       */
      han?: string;
      /**
       * 書評掲載日
       */
      appearance?: string;
      /**
       * 投稿ユーザー
       */
      post_user?: string;
      /**
       * 区分ID
       */
      kubun_id?: number;
      /**
       * 情報源
       */
      source?: string;
      /**
       * 朝刊・夕刊
       */
      choyukan?: string;
      /**
       * 情報源ID
       */
      source_id?: number;
      /**
       * 評者
       */
      reviewer?: string;
      /**
       * 号
       */
      gou?: string;
      /**
       * リンク
       */
      link?: string;
    }[];
    /**
     * 版元情報
     */
    hanmotoinfo?: {
      /**
       * 名前
       */
      name?: string;
      /**
       * よみ
       */
      yomi?: string;
      /**
       * URL
       */
      url?: string;
      /**
       * Twitterアドレス
       */
      twitter?: string;
      /**
       * Facebookアドレス
       */
      facebook?: string;
    };
    /**
     * 発売元
     */
    hatsubai?: string;
    /**
     * 発売元よみ
     */
    hatsubaiyomi?: string;
    /**
     * 不明
     */
    bikoujpo?: string;
    /**
     * 不明
     */
    storelink?: string;
  };
  /**
   * 書誌の概要
   */
  summary?: {
    /**
     * ISBN
     */
    isbn: string;
    /**
     * 書名
     */
    title: string;
    /**
     * 巻号
     */
    volume: string;
    /**
     * シリーズ名
     */
    series: string;
    /**
     * 著者名
     */
    author: string;
    /**
     * 出版者
     */
    /**
     * 出版年月
     */
    pubdate: string;
    /**
     * 書影URL
     */
    cover: string;
  };
}
